id: STMOriginal-5-10
pretrained: backup/STMOriginal-2020_05_08-19_27_48/best_metric_MeanIoU.pth
seed: 3698
model:
    name: STMOriginal
    args:
optimizer:
    name: SGD
    args:
        lr: 0.0005
        momentum: 0.5
loss:
    name: CrossEntropyLoss
    args:
metric:
    - name: MeanIoU
      args:
          nclasses: 2
    #- name: PixelAccuracy
    #  args:
    #      nclasses: 2
    #- name: DiceScore
    #  args:
    #      nclasses: 2
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 5
        verbose: True
dataset:
    train:
        name: DAVISPairDataset
        args:
            root_path: data/DAVIS-trainval
            resolution: 480p_split
            phase: train
            mode: 2
            max_skip: 10
            max_npairs: 20
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: True
    val:
        name: DAVISPairDataset
        args:
            root_path: data/DAVIS-trainval
            resolution: 480p_split
            phase: val
            mode: 2
            max_npairs: 50
        loader:
            name: DataLoader
            args:
                batch_size: 1
trainer:
    nepochs: 50
    val_step: 1
    log_step: 1
