id: STM-FSS
pretrained: null #backup/STM-YVOS-Pretrain/best_metric_ModifiedMeanIoU.pth
seed: 3698
model:
    name: STMOriginal
    args:
optimizer:
    name: Adam
    args:
        lr: 0.0001
loss:
    name: CrossEntropyLoss
metric:
    - name: MeanIoU
      args:
          nclasses: 2
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 5
        verbose: True
dataset:
    train:
        name: FSSRandomDataset
        args:
            root: data/PASCAL-5i
            phase: 0_train
            n: 1
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: True
    val:
        name: FSSRandomDataset
        args:
            root: data/PASCAL-5i
            phase: 0_val
            n: 100
        loader:
            name: DataLoader
            args:
                batch_size: 1
trainer:
    nepochs: 50
    val_step: 1
    log_step: 1
