id: FSS-STM-PASCAL0
pretrained: null #backup/STM-YVOS-WarmUp2/best_metric_ModifiedMeanIoU.pth
seed: 3698
model:
    name: STMOriginal
    args:
optimizer:
    name: SGD
    args:
        lr: 0.0025
        momentum: 0.9
        nesterov: True
loss:
    name: FSSCELoss
metric:
    - name: FSSMeanIoU
      args:
          nclasses: 5
          ignore_index: 0
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 5
        verbose: True
dataset:
    train:
        name: FSSRandomDataset
        args:
            root: data/PASCAL-5i
            phase: 0_train
            n: 100 # FSS: 64, PASCAL: 3200
            is_train: True
        loader:
            name: DataLoader
            args:
                batch_size: 4
                shuffle: True
    val:
        name: FSSRandomDataset
        args:
            root: data/PASCAL-5i
            phase: 0_val
            n: 500
        loader:
            name: DataLoader
            args:
                batch_size: 16
trainer:
    nepochs: 50
    val_step: 1
    log_step: 1
