id: STM-FSS
pretrained: null #backup/STM-YVOS-Pretrain/best_metric_ModifiedMeanIoU.pth
seed: 3698
model:
    name: STMOriginal
    args:
optimizer:
    name: Adam
    args:
        lr: 0.0001
loss:
    name: MultiCELoss
metric:
    - name: ModifiedMeanIoU
      args:
          nclasses: 2
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 5
        verbose: True
dataset:
    train:
        name: DAVISPairRandomDataset
        args:
            root_path: data/FSS-1000
            resolution: 480p
            phase: train
            year: 2020
            mode: 0
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: True
    val:
        name: DAVISPairDataset
        args:
            root_path: data/FSS-1000
            resolution: 480p
            phase: test
            year: 2020
            mode: 1
            is_train: False
        loader:
            name: DataLoader
            args:
                batch_size: 1
trainer:
    nepochs: 50
    val_step: 1
    log_step: 1
