id: STM-YVOS-WarmUp
pretrained: backup/STM-YVOS-Pretrain/best_metric_ModifiedMeanIoU.pth
seed: 3698
model:
    name: STMOriginal
    args:
optimizer:
    name: Adam
    args:
        lr: 0.0001
loss:
    name: MultiCELoss
metric:
    - name: ModifiedMeanIoU
      args:
          nclasses: 11
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 5
        verbose: True
dataset:
    train:
        name: DAVISPairRandomDataset
        args:
            root_path: data/YVOS-train
            resolution: 480p
            phase: train
            mode: 2
            max_skip: 5
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: True
    val:
        name: DAVISTripletDataset
        args:
            root_path: data/DAVIS-trainval
            resolution: 480p
            phase: val
            mode: 1
            is_train: False
        loader:
            name: DataLoader
            args:
                batch_size: 1
trainer:
    nepochs: 50
    val_step: 1
    log_step: 1
