id: FSS-STM-PASCAL0
pretrained: null #runs/FSS-STM-PASCAL0-2020_06_25-12_56_56/best_metric_FSSMeanIoU.pth
seed: 3698
model:
    name: STMOriginal
    args:
optimizer:
    name: SGD
    args:
        lr: 0.0001
        momentum: 0.9
        weight_decay: 0.0005
        nesterov: True
loss:
    name: FSSCELoss
metric:
    - name: FSSMeanIoU
      args:
          nclasses: 5
          ignore_index: 0
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 5
        verbose: True
dataset:
    train:
        name: FSS_Dataset
        args:
            data_dir: ../crnet_simple/data/VOC2012
            fold: 0
            #root: data/PASCAL-5i
            #phase: 0_train
            #n: 500 # FSS: 64, PASCAL: 3200
            #is_train: True
        loader:
            name: DataLoader
            args:
                batch_size: 16
                shuffle: True
    val:
        name: FSS_ValDataset
        args:
            data_dir: ../crnet_simple/data/VOC2012
            fold: 0
            #root: data/PASCAL-5i
            #phase: 0_val
            #n: 500
            #is_train: False
        loader:
            name: DataLoader
            args:
                batch_size: 1
trainer:
    nepochs: 50
    val_step: 1
    log_step: 1
